name: Staging Teardown

on:
  pull_request:
    types: [closed]

env:
  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
  GH_ENV_APP_ID: ${{ secrets.GH_ENV_APP_ID }}
  GH_ENV_APP_PRIVATE_KEY: ${{ secrets.GH_ENV_APP_PRIVATE_KEY }}
  NUXT_DEPLOY_TAG: mark4-nuxt-stage-${{ github.event.number }}

jobs:
  cf_teardown:
    name: Delete Staging Cloudflare Workers
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Teardown Nuxt
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ env.CF_API_TOKEN }}
          command: delete --name ${{ env.NUXT_DEPLOY_TAG }}
          workingDirectory: nuxt

  gh_delete_deploy_env:
    name: Delete Github Deploy Environment
    runs-on: ubuntu-latest

    steps:
      - name: Get GitHub App Token
        uses: navikt/github-app-token-generator@a3831f44404199df32d8f39f7c0ad9bb8fa18b1c
        id: get-token
        with:
          app-id: ${{ env.GH_ENV_APP_ID }}
          private-key: ${{ env.GH_ENV_APP_PRIVATE_KEY }}

      - name: Delete Github Deploy Environment
        uses: strumwolf/delete-deployment-environment@v3
        with:
          token: ${{ steps.get-token.outputs.token }}
          environment: nuxt-stage-${{ github.event.number }}
